### ISSUE TITLE
when downloading the code, bzr says that it's not checking SSL certificate for xmlrpc.launchpad.net

### ISSUE THREAD

**Issue by sp-1234** [caskformula/homebrew-caskformula#3]
if I understand right, this means that in this case bzr can download anything at all and it'd be executed blindly — not good!

log of the trial:

```
$ brew install inkscape --HEAD --with-gtk3
==> Installing inkscape from caskformula/caskformula
==> Cloning lp:inkscape
Not checking SSL certificate for xmlrpc.launchpad.net.
You have not informed bzr of your Launchpad ID, and you must do this to
write to Launchpad or access private data.  See "bzr help launchpad-login".
```
(I interrupted the installation at this point)

**Comment by tghs** [comment]
Thanks for reporting this. It looks like this might be due to a problem with homebrew's bzr build (let me know if you're using bzr from somewhere else)/default configuration. That message appears when the bzr ssl.cert_reqs config value is set to `none`.

Looking at the output of `bzr config ssl.cert_reqs` gives me `none`. From looking at the source code, the default value should be `required`.

Trying to force the correct config value with `bzr config ssl.cert_reqs=required` doesn't seem stop the warning from appearing though.

Note: the warning can be inhibited by specifying a launchpad account, as the output advises.

I recommend taking this issue upsteam and raise an issue against [the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazaar.rb) and if that doesn't go anywhere, take it to the [bazaar project](https://bazaar.canonical.com/en/).

For this, there are plain bzr commands that demonstrate this behaviour. E.g.: `bzr launchpad-login`

Please link in this thread to any upstream tracking of this issue, if you take it elsewhere.

I'll leave this bug open. Most likely it'll get closed when Inkscape moves to git (happening in the 0.93 development cycle), and this issue becomes moot.

**Comment by sp-1234** [comment]
>let me know if you're using bzr from somewhere else

no, I didn't install bzr myself. it should be from homebrew with default options

**Comment by sp-1234** [comment]
> when Inkscape moves to git

definitely a must.

**Comment by tghs** [comment]
Inkscape has now switched to git from bzr, so I've updated `--HEAD` builds to use git instead. Since we're no longer using bzr, I'm closing this issue.
